### ISSUE TITLE
lien pdf inaccessible 

### ISSUE THREAD

**Issue by GuyliannEngels** [mussoi-lisa/mussoi-lisa-blog#1]
@mussoi-lisa ,

Ton article pdf n'est pas accessible sur ton blog. C'est normal tu as mis un lien local

corrige cela vite 

Bonne journée

**Comment by mussoi-lisa** [comment]
Comment je peux corriger ca ?
Le 22 oct. 2019 à 10:27, Guyliann Engels <notifications@github.com<mailto:notifications@github.com>> a écrit :


@mussoi-lisa<https://github.com/mussoi-lisa> ,

Ton article pdf n'est pas accessible sur ton blog. C'est normal tu as mis un lien local

corrige cela vite

Bonne journée

**Comment by GuyliannEngels** [comment]
C'est très simple :)

au lieu d'employer le lien 

<http://localhost:8719/files/shared/projects/mussoi-lisa-blog/_posts/2019-09-18-article-1/article%201%20anglais.pdf>

Tu dois employer le lien 

https://github.com/mussoi-lisa/mussoi-lisa-blog/blob/master/_posts/2019-09-18-article-1/article%201%20anglais.pdf

**Comment by GuyliannEngels** [comment]
J'ai envoyé un message pour le cours de SDD1 avec une explication détaillée

**Comment by mussoi-lisa** [comment]
Merci beaucoup Guyliann :)
Le 22 oct. 2019 à 10:33, Guyliann Engels <notifications@github.com<mailto:notifications@github.com>> a écrit :

https://github.com/mussoi-lisa/mussoi-lisa-blog/blob/master/_posts/2019-09-18-article-1/article%201%20anglais.pdf

**Comment by mussoi-lisa** [comment]
Message que je n’ai pas reçu du coup :p
Le 22 oct. 2019 à 10:34, Guyliann Engels <notifications@github.com<mailto:notifications@github.com>> a écrit :


J'ai envoyé un message pour le cours de SDD1 avec une explication détaillée

**Comment by GuyliannEngels** [comment]
Pour avoir les infos sur le blog, il est préférable que tu sois inscrite au cours SDD1 sur moodle

**Comment by mussoi-lisa** [comment]
Je vais faire ca tout de suite !
Le 22 oct. 2019 à 10:36, Guyliann Engels <notifications@github.com<mailto:notifications@github.com>> a écrit :


Pour avoir les infos sur le blog, il est préférable que tu sois inscrite au cours SDD1 sur moodle
